[build]
  publish = "dist/client/browser"
  command = "ng build --prod"

[build.environment]
  NODE_VERSION = "18.19"

[context.deploy-preview]
  command = "ng build --prod"

[context.branch-deploy]
  command = "ng build --prod"

[context.production]
  command = "ng build --prod"
