[build]
  publish = "dist/client/browser"
  command = "ng build --configuration production"

[build.environment]
  NODE_VERSION = "18.19"

[context.deploy-preview]
  command = "ng build --configuration production"

[context.branch-deploy]
  command = "ng build --configuration production"

[context.production]
  command = "ng build --configuration production"

  [[redirects]]
  from="/*"
  to = "/index.html"
  status = 200